### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mrayson** [mrayson/sfoda#6]
- [ ] Make windows installable (see #4 and #3)
- [ ] Make [mycurrents](https://bitbucket.org/mrayson/mycurrents.git) into a sub-module
- [ ] Use PyShp instead of gdal
- [ ] #7
- [ ] Update myspectra code (include filter etc)
- [ ] Insert 2d filter code
- [ ] Insert ROMS interpolation code
- [ ] Change interface between SUNTANS unstructured grid and xarray
- [ ] ...

**Comment by mrayson** [comment]
ping @iosonobert

**Comment by iosonobert** [comment]
Did you see pull request?

**Comment by mrayson** [comment]
I did just now. Cheers!
